import Login from "@/components/login/Login";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Login - secure-short</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </>
  );
}
